# ESPHome configuration for the IVT Rego 600/601 heat pump controller.
# https://esphome.io/index.html
esphome:
  name: heatpumpctrl
  friendly_name: IVT Heatpump
  area: Heating room
  project:
    name: "BlueAndi.IVTRego6xxControl"
    version: "1.5.0"
  includes:
    - lib/Rego6xx
    - lib/Utilities
  platformio_options:
    build_flags:
      - -I src/Rego6xx
      - -I src/Utilities

# Platform configuration.
# https://esphome.io/components/esp32.html
esp32:
  board: esp32-poe-iso
  framework:
    type: arduino

# Enable logging.
# https://esphome.io/components/logger.html
logger:
  level: DEBUG

# Enable Home Assistant API.
# https://esphome.io/components/api.html
api:
  password: ""
  reboot_timeout: 0s # If you enable MQTT and you do not use the Native API Component, you must set reboot_timeout: 0s, otherwise the ESP will reboot every 15 minutes because no client connected to the native API.

# Enable OTA updates.
# https://esphome.io/components/ota.html
ota:
  - platform: esphome
    password: ""

# Enable ethernet interface.
# https://esphome.io/components/ethernet.html
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO17
    mode: CLK_OUT
  phy_addr: 0
  power_pin:
    number: GPIO12
    ignore_strapping_warning: true

# Configure UART interface for heatpump communication.
# https://esphome.io/components/uart.html
#
# Use UART1 on UEXT connector.
uart:
  id: uart_heatpump
  rx_pin: GPIO36
  tx_pin: GPIO4
  baud_rate: 19200
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      timeout: 500ms

# Webserver configuration
# https://esphome.io/components/web_server.html
web_server:
  port: 80
  version: 3
  sorting_groups:
    - id: sg_front_panel
      name: "Front panel"
      sorting_weight: 10
    - id: sg_temperatures
      name: "Temperatures"
      sorting_weight: 20
    - id: sg_settings
      name: "Settings"
      sorting_weight: 30

# MQTT configuration
mqtt:
  broker: !secret mqtt_broker
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_password
  reboot_timeout: 0s
  birth_message:
    topic: heatpumpctrl/status
    payload: "online"
  will_message:
    topic: heatpumpctrl/status
    payload: "offline"

# Custom component configuration
external_components:
  - source:
      type: local
      path: src

ivt_rego6xx_ctrl:
  id: ivt_rego6xx_ctrl_id
  uart_id: uart_heatpump

# Sensor configuration
# https://esphome.io/components/sensor/index.html
#
# ivt_rego6xx_ctrl_id  : The ID of the custom component.
# ivt_rego6xx_ctrl_cmd : The command to send to the heat pump.
# ivt_rego6xx_ctrl_addr: The address to read by the command.
#
# Important: The system register response will be interpreted as float.
sensor:
  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x02 # Read system register
    ivt_rego6xx_ctrl_addr: 0x0209
    name: gt1
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    web_server:
      sorting_group_id: sg_temperatures
      sorting_weight: 10

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x02 # Read system register
    ivt_rego6xx_ctrl_addr: 0x020a
    name: gt2
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    web_server:
      sorting_group_id: sg_temperatures
      sorting_weight: 20

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x02 # Read system register
    ivt_rego6xx_ctrl_addr: 0x020b
    name: gt3
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    web_server:
      sorting_group_id: sg_temperatures
      sorting_weight: 30

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x02 # Read system register
    ivt_rego6xx_ctrl_addr: 0x020c
    name: gt4
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    web_server:
      sorting_group_id: sg_temperatures
      sorting_weight: 40

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x02 # Read system register
    ivt_rego6xx_ctrl_addr: 0x020d
    name: gt5
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    web_server:
      sorting_group_id: sg_temperatures
      sorting_weight: 50

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x02 # Read system register
    ivt_rego6xx_ctrl_addr: 0x020e
    name: gt6
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    web_server:
      sorting_group_id: sg_temperatures
      sorting_weight: 60

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x02 # Read system register
    ivt_rego6xx_ctrl_addr: 0x020f
    name: gt8
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    web_server:
      sorting_group_id: sg_temperatures
      sorting_weight: 70

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x02 # Read system register
    ivt_rego6xx_ctrl_addr: 0x0210
    name: gt9
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    web_server:
      sorting_group_id: sg_temperatures
      sorting_weight: 80

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x02 # Read system register
    ivt_rego6xx_ctrl_addr: 0x0211
    name: gt10
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    web_server:
      sorting_group_id: sg_temperatures
      sorting_weight: 90

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x02 # Read system register
    ivt_rego6xx_ctrl_addr: 0x0212
    name: gt11
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    web_server:
      sorting_group_id: sg_temperatures
      sorting_weight: 100

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x02 # Read system register
    ivt_rego6xx_ctrl_addr: 0x0213
    name: gt3x
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    web_server:
      sorting_group_id: sg_temperatures
      sorting_weight: 110

# Binary sensor configuration
# https://esphome.io/components/binary_sensor/index.html
#
# ivt_rego6xx_ctrl_id  : The ID of the custom component.
# ivt_rego6xx_ctrl_cmd : The command to send to the heat pump.
# ivt_rego6xx_ctrl_addr: The address to read by the command.
#
# Important: The system register response will be interpreted as boolean.
binary_sensor:
  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x00 # Read front panel register
    ivt_rego6xx_ctrl_addr: 0x0012
    name: power led
    icon: mdi:led-outline
    web_server:
      sorting_group_id: sg_front_panel
      sorting_weight: 10

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x00 # Read front panel register
    ivt_rego6xx_ctrl_addr: 0x0013
    name: pump led
    icon: mdi:led-outline
    web_server:
      sorting_group_id: sg_front_panel
      sorting_weight: 20

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x00 # Read front panel register
    ivt_rego6xx_ctrl_addr: 0x0014
    name: heating led
    icon: mdi:led-outline
    web_server:
      sorting_group_id: sg_front_panel
      sorting_weight: 30

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x00 # Read front panel register
    ivt_rego6xx_ctrl_addr: 0x0015
    name: boiler led
    icon: mdi:led-outline
    web_server:
      sorting_group_id: sg_front_panel
      sorting_weight: 40

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x00 # Read front panel register
    ivt_rego6xx_ctrl_addr: 0x0016
    name: alarm led
    icon: mdi:led-outline
    web_server:
      sorting_group_id: sg_front_panel
      sorting_weight: 50

# Text sensor configuration
# https://esphome.io/components/text_sensor/index.html
#
# ivt_rego6xx_ctrl_id  : The ID of the custom component.
# ivt_rego6xx_ctrl_cmd : The command to send to the heat pump.
# ivt_rego6xx_ctrl_addr: The address to read by the command.
#
# Important: The system register response will be interpreted as string.
text_sensor:
  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x20 # Read display register
    ivt_rego6xx_ctrl_addr: 0x0000 # Display row 1
    icon: mdi:format-textbox
    name: display row 1
    web_server:
      sorting_group_id: sg_front_panel
      sorting_weight: 60

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x20 # Read display register
    ivt_rego6xx_ctrl_addr: 0x0001 # Display row 2
    name: display row 2
    icon: mdi:format-textbox
    web_server:
      sorting_group_id: sg_front_panel
      sorting_weight: 70

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x20 # Read display register
    ivt_rego6xx_ctrl_addr: 0x0002 # Display row 3
    name: display row 3
    icon: mdi:format-textbox
    web_server:
      sorting_group_id: sg_front_panel
      sorting_weight: 80

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x20 # Read display register
    ivt_rego6xx_ctrl_addr: 0x0003 # Display row 4
    name: display row 4
    icon: mdi:format-textbox
    web_server:
      sorting_group_id: sg_front_panel
      sorting_weight: 90

# Button configuration
# https://esphome.io/components/button/index.html
#
# ivt_rego6xx_ctrl_id  : The ID of the custom component.
# ivt_rego6xx_ctrl_cmd : The command to send to the heat pump.
# ivt_rego6xx_ctrl_addr: The address to write by the command.
# ivt_rego6xx_ctrl_value: The value to write by the command.
button:
  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x01 # Write to front panel register
    ivt_rego6xx_ctrl_addr: 0x0008
    ivt_rego6xx_ctrl_value: 0x000001
    name: power button
    icon: mdi:power
    web_server:
      sorting_group_id: sg_front_panel
      sorting_weight: 100

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x01 # Write to front panel register
    ivt_rego6xx_ctrl_addr: 0x0009
    ivt_rego6xx_ctrl_value: 0x000001
    name: left button
    icon: mdi:button-pointer
    web_server:
      sorting_group_id: sg_front_panel
      sorting_weight: 110

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x01 # Write to front panel register
    ivt_rego6xx_ctrl_addr: 0x000A
    ivt_rego6xx_ctrl_value: 0x000001
    name: middle button
    icon: mdi:button-pointer
    web_server:
      sorting_group_id: sg_front_panel
      sorting_weight: 120

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x01 # Write to front panel register
    ivt_rego6xx_ctrl_addr: 0x000B
    ivt_rego6xx_ctrl_value: 0x000001
    name: right button
    icon: mdi:button-pointer
    web_server:
      sorting_group_id: sg_front_panel
      sorting_weight: 130

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x01 # Write to front panel register
    ivt_rego6xx_ctrl_addr: 0x0044
    ivt_rego6xx_ctrl_value: 0x1FFFFF
    name: turn wheel left
    icon: mdi:arrow-left-top
    web_server:
      sorting_group_id: sg_front_panel
      sorting_weight: 140

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd: 0x01 # Write to front panel register
    ivt_rego6xx_ctrl_addr: 0x0044
    ivt_rego6xx_ctrl_value: 0x000001
    name: turn wheel right
    icon: mdi:arrow-right-top
    web_server:
      sorting_group_id: sg_front_panel
      sorting_weight: 150

# Number configuration
# https://esphome.io/components/number/index.html
#
# ivt_rego6xx_ctrl_id  : The ID of the custom component.
# ivt_rego6xx_ctrl_cmd : The command to send to the heat pump.
# ivt_rego6xx_ctrl_addr: The address to write by the command.
# ivt_rego6xx_ctrl_min_value: The minimum value for the number.
# ivt_rego6xx_ctrl_max_value: The maximum value for the number.
# ivt_rego6xx_ctrl_step: The step size for the number.
number:
  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd_read: 0x02 # Read system register
    ivt_rego6xx_ctrl_cmd_write: 0x03 # Write system register
    ivt_rego6xx_ctrl_addr: 0x006E
    ivt_rego6xx_ctrl_min_value: 0
    ivt_rego6xx_ctrl_max_value: 100
    ivt_rego6xx_ctrl_step: 0.5
    name: gt1 target
    unit_of_measurement: "°C"
    device_class: temperature
    icon: mdi:thermometer
    web_server:
      sorting_group_id: sg_settings
      sorting_weight: 10

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd_read: 0x02 # Read system register
    ivt_rego6xx_ctrl_cmd_write: 0x03 # Write system register
    ivt_rego6xx_ctrl_addr: 0x006F
    ivt_rego6xx_ctrl_min_value: 0
    ivt_rego6xx_ctrl_max_value: 100
    ivt_rego6xx_ctrl_step: 0.5
    name: gt1 on
    unit_of_measurement: "°C"
    device_class: temperature
    icon: mdi:thermometer
    web_server:
      sorting_group_id: sg_settings
      sorting_weight: 20

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd_read: 0x02 # Read system register
    ivt_rego6xx_ctrl_cmd_write: 0x03 # Write system register
    ivt_rego6xx_ctrl_addr: 0x0070
    ivt_rego6xx_ctrl_min_value: 0
    ivt_rego6xx_ctrl_max_value: 100
    ivt_rego6xx_ctrl_step: 0.5
    name: gt1 off
    unit_of_measurement: "°C"
    device_class: temperature
    icon: mdi:thermometer
    web_server:
      sorting_group_id: sg_settings
      sorting_weight: 30

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd_read: 0x02 # Read system register
    ivt_rego6xx_ctrl_cmd_write: 0x03 # Write system register
    ivt_rego6xx_ctrl_addr: 0x002B
    ivt_rego6xx_ctrl_min_value: 0
    ivt_rego6xx_ctrl_max_value: 100
    ivt_rego6xx_ctrl_step: 0.5
    name: gt3 target
    unit_of_measurement: "°C"
    device_class: temperature
    icon: mdi:thermometer
    web_server:
      sorting_group_id: sg_settings
      sorting_weight: 40

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd_read: 0x02 # Read system register
    ivt_rego6xx_ctrl_cmd_write: 0x03 # Write system register
    ivt_rego6xx_ctrl_addr: 0x0073
    ivt_rego6xx_ctrl_min_value: 0
    ivt_rego6xx_ctrl_max_value: 100
    ivt_rego6xx_ctrl_step: 0.5
    name: gt3 on
    unit_of_measurement: "°C"
    device_class: temperature
    icon: mdi:thermometer
    web_server:
      sorting_group_id: sg_settings
      sorting_weight: 50

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd_read: 0x02 # Read system register
    ivt_rego6xx_ctrl_cmd_write: 0x03 # Write system register
    ivt_rego6xx_ctrl_addr: 0x0074
    ivt_rego6xx_ctrl_min_value: 0
    ivt_rego6xx_ctrl_max_value: 100
    ivt_rego6xx_ctrl_step: 0.5
    name: gt3 off
    unit_of_measurement: "°C"
    device_class: temperature
    icon: mdi:thermometer
    web_server:
      sorting_group_id: sg_settings
      sorting_weight: 60

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd_read: 0x02 # Read system register
    ivt_rego6xx_ctrl_cmd_write: 0x03 # Write system register
    ivt_rego6xx_ctrl_addr: 0x006D
    ivt_rego6xx_ctrl_min_value: 0
    ivt_rego6xx_ctrl_max_value: 100
    ivt_rego6xx_ctrl_step: 0.5
    name: gt4 target
    unit_of_measurement: "°C"
    device_class: temperature
    icon: mdi:thermometer
    web_server:
      sorting_group_id: sg_settings
      sorting_weight: 70

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id
    ivt_rego6xx_ctrl_cmd_read: 0x02 # Read system register
    ivt_rego6xx_ctrl_cmd_write: 0x03 # Write system register
    ivt_rego6xx_ctrl_addr: 0x006C
    ivt_rego6xx_ctrl_min_value: 0
    ivt_rego6xx_ctrl_max_value: 100
    ivt_rego6xx_ctrl_step: 0.5
    name: add heat power
    unit_of_measurement: "%"
    device_class: temperature
    icon: mdi:heat-pump
    web_server:
      sorting_group_id: sg_settings
      sorting_weight: 80
