# ESPHome configuration for the IVT Rego 600/601 heat pump controller
esphome:
  name: heatpumpctrl
  includes:
    - lib/Rego6xx
    - lib/Utilities
  platformio_options:
    build_flags:
      - -I src/Rego6xx
      - -I src/Utilities

# Platform configuration
esp32:
  board: esp32-poe-iso
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: ""

# Enable OTA updates
ota:
  - platform: esphome
    password: ""

# Enable ethernet interface
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin:
    number: GPIO12
    ignore_strapping_warning: true

# Configure UART interface for heatpump communication
uart:
  id: uart_heatpump
  rx_pin: GPIO4
  tx_pin: GPIO3
  baud_rate: 115200

# Webserver configuration
web_server:
  port: 80

# MQTT configuration
mqtt:
  broker: homeassistant.fritz.box
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_password
  reboot_timeout: 0s
  birth_message:
    topic: devices/heatpumpctrl
    payload: 'online'
  will_message:
    topic: devices/heatpumpctrl
    payload: 'offline'

# Custom component configuration
external_components:
  - source:
      type: local
      path: src

ivt_rego6xx_ctrl:
  id: ivt_rego6xx_ctrl_id
  uart_id: uart_heatpump

sensor:
  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id # Reference to the custom component
    ivt_rego6xx_variable: gt1
    name: Radiator return GT1
    unit_of_measurement: °C
    state_class: measurement

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id # Reference to the custom component
    ivt_rego6xx_variable: gt2
    name: Outddor GT2
    unit_of_measurement: °C
    state_class: measurement

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id # Reference to the custom component
    ivt_rego6xx_variable: gt3
    name: Hot water GT3
    unit_of_measurement: °C
    state_class: measurement

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id # Reference to the custom component
    ivt_rego6xx_variable: gt4
    name: Forward GT4
    unit_of_measurement: °C
    state_class: measurement

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id # Reference to the custom component
    ivt_rego6xx_variable: gt8
    name: Heat fluid out GT8
    unit_of_measurement: °C
    state_class: measurement

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id # Reference to the custom component
    ivt_rego6xx_variable: gt9
    name: Heat fluid in GT9
    unit_of_measurement: °C
    state_class: measurement

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id # Reference to the custom component
    ivt_rego6xx_variable: gt10
    name: Cold fluid in GT10
    unit_of_measurement: °C
    state_class: measurement

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id # Reference to the custom component
    ivt_rego6xx_variable: gt11
    name: Cold fluid out GT11
    unit_of_measurement: °C
    state_class: measurement

  - platform: ivt_rego6xx_ctrl
    ivt_rego6xx_ctrl_id: ivt_rego6xx_ctrl_id # Reference to the custom component
    ivt_rego6xx_variable: gt3x
    name: External hot water GT3X
    unit_of_measurement: °C
    state_class: measurement
